# Please check README.md for more details on any configuration
# Powered by: https://www.mkdocs.org/

site_name: First Docs (1.0.0)
site_url: https://laithoura.github.io/learn-mkdocs/
          # DEV : http://127.0.0.1:8000/
          # PROD: https://laithoura.github.io/learn-mkdocs/
extra:
    version: 1.0
    contextPath: "/learn-mkdocs/" # Dev="/" ; PRD="/learn-mkdocs/"
    pageNotFoundTitle: "Page Not Found"

extra_css:
    - css/custom.css?v=1.0.0 # Increase version whenever you modify the file to avoid caching issue

extra_javascript:
    - js/custom.js?v=1.0.0 # Increase version whenever you modify the file to avoid caching issue

nav:
    - Home: index.md
    - Copy KYC: ./kyc/index.md
    - Meta Data: meta.md
    - Learn Markdown: markdown.md
    - 'User Guide':
        - 'Writing your docs': './guide/user/writing-your-docs.md'
        - 'Styling your docs': './guide/user/styling-your-docs.md'
    - 'Developer Guide':
        - 'Writing my docs': './guide/developer/writing-your-docs.md'
        - 'Styling my docs': './guide/developer/styling-your-docs.md'
    - Help: ./help/index.md
    
theme:
    name: readthedocs # `mkdocs` | `readthedocs`
    custom_dir: custom_theme/
    shortcuts: # This feature doesn't with with `readthedocs`. So, in order use this feature you have to use `mkdocs`
        help: 191    # ?
        next: 78     # n
        previous: 80 # p
        search: 83   # s
    prev_next_buttons_location: top
    navigation_depth: 4 # default: 4
markdown_extensions:
    - toc:
        permalink: "#"
        baselevel: 1
        separator: "-"